version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
build:
  commands:
   - sudo yum update
   - sudo yum install python3-pip
   - pip3 install pymsteams
   - touch python.py
   - echo "import pymsteams" | tee -a python.py 
   - echo "myTeamsMessage = pymsteams.connectorcard(\"https://zertain.webhook.office.com/webhookb2/2e39c5d4-9f28-487f-b81b-e914e19601cc@bfea0d66-7869-4844-b196-e530d72f8652/IncomingWebhook/d43ed4de8aba40f892c5709996659103/0780dee0-b73d-46dc-a975-3c463c2d5855\")" | tee -a python.py
   - echo "myTeamsMessage.text(\"build failed\")" | tee -a python.py
   - echo "myTeamsMessage.send()" | tee -a python.py
   - python3 python.py     
